package main

import "github.com/Zyko0/go-sdl3/sdl"

// Layout constants matching testcontroller.c
const (
	TITLE_HEIGHT   = 48.0
	PANEL_SPACING  = 25.0
	PANEL_WIDTH    = 250.0
	GAMEPAD_WIDTH  = 512.0
	GAMEPAD_HEIGHT = 560.0
	BUTTON_MARGIN  = 16.0
	SCREEN_WIDTH   = PANEL_WIDTH + PANEL_SPACING + GAMEPAD_WIDTH + PANEL_SPACING + PANEL_WIDTH
	SCREEN_HEIGHT  = TITLE_HEIGHT + GAMEPAD_HEIGHT

	FONT_CHARACTER_SIZE = float32(sdl.DEBUG_TEXT_FONT_CHARACTER_SIZE)
	FONT_LINE_HEIGHT    = FONT_CHARACTER_SIZE + 2
)
